config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_scope :usuario do
    get "sign_out" => "devise/sessions#destroy"
    get "salir" => "devise/sessions#destroy",
      as: :terminar_sesion
    post "usuarios/iniciar_sesion", to: "devise/sessions#create"
    get "usuarios/iniciar_sesion",
      to: "devise/sessions#new",
      as: :iniciar_sesion

    # El siguiente para superar mala generación del action en el
    # formulario cuando se autentica mal (genera
    # /puntomontaje/puntomontaje/usuarios/sign_in )
    if Rails.configuration.relative_url_root != "/"
      ruta = File.join(
        Rails.configuration.relative_url_root,
        "usuarios/sign_in",
      )
      post ruta, to: "devise/sessions#create"
    end
  end
  devise_for :usuarios, skip: [:registrations], module: :devise
  as :usuario do
    get "usuarios/edit" => "devise/registrations#edit",
      :as => "editar_registro_usuario"
    put "usuarios/:id" => "devise/registrations#update",
      :as => "registro_usuario"
  end
  resources :usuarios, path_names: { new: "nuevo", edit: "edita" }
  get "/usuarios/foto/:id",
    to: "usuarios#foto",
    as: "usuarios_foto"

  root "cor1440_gen/hogar#index"

  mount Msip::Engine, at: "/", as: "msip"
  mount Mr519Gen::Engine, at: "/", as: "mr519_gen"
  mount Heb412Gen::Engine, at: "/", as: "heb412_gen"
  mount Cor1440Gen::Engine, at: "/", as: "cor1440_gen"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability < Cor1440Gen::Ability
  def tablasbasicas
    Msip::Ability::BASICAS_PROPIAS + BASICAS_PROPIAS - [
      ["Msip", "fuenteprensa"],
      ["Msip", "oficina"],
      ["Cor1440Gen", "proyecto"],
      ["Msip", "tdocumento"],
      ["Msip", "trelacion"],
      ["Msip", "tsitio"],
    ]
  end

  # Autorizacion con CanCanCan
  def initialize(usuario = nil)
    initialize_cor1440_gen(usuario)
    cannot(:read, Msip::Oficina)
    if !usuario || usuario.fechadeshabilitacion || !usuario.rol
      nil
    end
  end # initialize
end

app/models/usuario.rb
# frozen_string_literal: true

require "cor1440_gen/concerns/models/usuario"

class Usuario < ActiveRecord::Base
  include Cor1440Gen::Concerns::Models::Usuario

  has_attached_file :foto,
    path: (Msip.ruta_anexos.to_s + "/fotos/:id_:filename")

  validates_attachment :foto, content_type: {
    content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"],
  }

  validates :foto_file_name, length: { maximum: 255 }

  def rol_usuario
    # No tiene restricciones de oficina
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < Msip::ApplicationController
  protect_from_forgery with: :exception

  # Sin definición de autorización por ser utilidad
end

app/controllers/cor1440_gen/actividades_controller.rb
# frozen_string_literal: true

require_dependency "cor1440_gen/concerns/controllers/actividades_controller"

module Cor1440Gen
  class ActividadesController < Heb412Gen::ModelosController
    include Cor1440Gen::Concerns::Controllers::ActividadesController

    before_action :set_actividad,
      only: [:show, :edit, :update, :destroy],
      exclude: [:contar]
    load_and_authorize_resource class: Cor1440Gen::Actividad

    def edit
      edit_cor1440_gen
      @listadoasistencia = true
      render(layout: "application")
    end
  end
end

app/controllers/cor1440_gen/proyectosfinancieros_controller.rb
# frozen_string_literal: true

require_dependency "cor1440_gen/concerns/controllers/proyectosfinancieros_controller"

module Cor1440Gen
  class ProyectosfinancierosController < Heb412Gen::ModelosController
    include Cor1440Gen::Concerns::Controllers::ProyectosfinancierosController

    before_action :set_proyectofinanciero,
      only: [:show, :edit, :update, :destroy]
    skip_before_action :set_proyectofinanciero, only: [:validar]

    load_and_authorize_resource class: Cor1440Gen::Proyectofinanciero,
      only: [
        :new,
        :create,
        :destroy,
        :edit,
        :update,
        :index,
        :show,
        :objetivospf,
      ]

    def atributos_index
      [
        :id,
        :nombre,
      ] +
        [financiador_ids: []] +
        [
          :fechainicio_localizada,
          :fechacierre_localizada,
          :responsable,
          :proyectofinanciero_usuario,
        ] +
        [
          :compromisos,
          :monto,
          :observaciones,
          :objetivopf,
          :indicadorobjetivo,
          :resultadopf,
          :indicadorpf,
          :actividadpf,
        ]
    end

    def atributos_show
      atributos_index - [
        :objetivopf,
        :indicadorobjetivo,
        :resultadopf,
        :indicadorpf,
        :actividadpf,
      ] + [
        :marcologico,
        :caracterizacion,
        :beneficiario,
        :plantillahcm,
        :anexo_proyectofinanciero,
      ]
    end
  end
end

app/controllers/usuarios_controller.rb
# frozen_string_literal: true

require "cor1440_gen/concerns/controllers/usuarios_controller"

class UsuariosController < Msip::ModelosController
  include Cor1440Gen::Concerns::Controllers::UsuariosController

  # Sin definicion de autoridad por ser requerido por no autenticados

  def atributos_index
    [
      :id,
      :nusuario,
      :nombre,
      :email,
      :grupo_ids,
      :foto,
      :habilitado,
    ]
  end

  def atributos_form
    r = []
    if can?(:create, ::Usuario)
      r += [
        :nusuario,
        :nombre,
        :descripcion,
      ]
    end
    if can?(:manage, ::Usuario)
      r += [:rol]
    end
    if can?(:create, ::Usuario)
      r += [
        :email,
        :tema,
        :msip_grupo,
        :foto,
        :fechacreacion,
        :fechadeshabilitacion,
      ]
    end
    if can?(:manage, ::Usuario)
      r += [
        :idioma,
        :encrypted_password,
        :failed_attempts,
        :unlock_token,
        :locked_at,
      ]
    end
    r
  end

  def atributos_show
    r = []
    if can?(:read, ::Usuario)
      r += [
        :nusuario,
        :id,
        :nombre,
        :grupos,
        :email,
        :foto,
      ]
    end
    if can?(:manage, ::Usuario)
      r += [
        :rol,
        :idioma,
        :encrypted_password,
        :fechacreacion_localizada,
        :fechadeshabilitacion_localizada,
        :failed_attempts,
        :unlock_token,
        :locked_at,
      ]
    end
    r
  end

  def atributos_show_json
    atributos_show
  end

  def index_reordenar(c)
    if !params || !params[:filtro] || !params[:filtro][:bushabilitado]
      c = c.where("usuario.fechadeshabilitacion IS NULL")
    end
    c = c.reorder([:nombre])
    c
  end

  def foto
    unless params[:id].nil?
      @usuario = Usuario.find(params[:id].to_i)
      ruta = @usuario.foto_file_name
      n = if !ruta.nil?
        format(
          Msip.ruta_anexos.to_s + "/fotos/%d_%s",
          @usuario.id.to_i,
          File.basename(ruta),
        )
      else
        Msip.ruta_anexos.to_s + "/fotos/predeterminada.png"
      end
      logger.debug("Descargando #{n}")
      send_file(n, x_sendfile: true)
    end
  end

  def lista_params
    p = lista_params_cor1440_gen + [:foto]
    p
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<% content_for :title do %>
    <%= Msip.titulo %>
<% end %>

<% content_for :menu do %>
  <%= grupo_menus_prosidebar do %>
    <%= opcion_menu_prosidebar "Inicio", 
      Rails.configuration.relative_url_root.to_s %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo_prosidebar "Proyectos", 'ri-briefcase-4-fill', nil do %>
        <%= opcion_menu_prosidebar "Listado", 
          cor1440_gen.proyectosfinancieros_path %>
        <%= opcion_menu_prosidebar "Validar", 
          cor1440_gen.validar_proyectosfinancieros_path %>
        <% if can? :manage, Cor1440Gen::Mindicadorpf %>
          <%= opcion_menu_prosidebar "Medir Indicadores", 
            cor1440_gen.mindicadorespf_path %>
        <% end %>
      <% end %>
      <%= despliega_abajo_prosidebar "Actividades", 'ri-riding-fill', nil do %>
        <%= opcion_menu_prosidebar "Listado", 
          cor1440_gen.actividades_path %>
        <%= opcion_menu_prosidebar "Contar por actividad de marco lógico", 
          cor1440_gen.contar_actividades_path %>
        <%= opcion_menu_prosidebar "Contar por beneficiario y actividad de marco lógico",
          cor1440_gen.contar_actividades_beneficiarios_path %>
        <% if can? :manage, ::Msip::Orgsocial %>
          <%= opcion_menu_prosidebar "Organizaciones sociales", 
            msip.orgsociales_path %>
        <% end %>
        <% if can? :manage, ::Msip::Persona %>
          <%= opcion_menu_prosidebar "Beneficiarios", msip.personas_path %>
        <% end %>
      <% end %>
    <% end %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo_prosidebar "Documentos y plantillas", 
        'ri-book-open-fill', nil do %>
        <%= opcion_menu_prosidebar "Nube", heb412_gen.sisini_path %>
        <% if can? :manage, ::Heb412Gen::Plantillahcm %>
          <%= opcion_menu_prosidebar "Plantillas para listados en hojas de calculo",
            heb412_gen.plantillashcm_path %>
        <% end %>
        <% if can? :manage, ::Heb412Gen::Plantillahcr %>
          <%= opcion_menu_prosidebar "Plantillas para un registro en hoja de calculo",
            heb412_gen.plantillashcr_path %>
        <% end %>
      <% end %>
      <%= despliega_abajo_prosidebar "Administrar", 'ri-settings-4-fill', nil do %>
        <%= opcion_menu_prosidebar "Clave y tema", 
          main_app.editar_registro_usuario_path %>
        <% if current_usuario.rol == Ability::ROLADMIN %>
          <%= opcion_menu_prosidebar "Usuarios", main_app.usuarios_path %>
        <% end %>
        <% if can? :manage, Mr519Gen::Formulario %>
          <%= opcion_menu_prosidebar "Formularios", 
            mr519_gen.formularios_path %>
        <% end %>
        <% if current_usuario.rol == Ability::ROLADMIN %>
          <%= opcion_menu_prosidebar "Tablas básicas", 
            msip.tablasbasicas_path %>
        <% end %>
      <% end %>
      <%= opcion_menu_prosidebar "Salir #{current_usuario.nusuario}", 
        main_app.terminar_sesion_path %>
    <% else %>
      <%= opcion_menu_prosidebar "Acerca de", 
        msip.acercade_path %>
      <%= opcion_menu_prosidebar "Iniciar Sesión", 
        main_app.iniciar_sesion_path %>
    <% end %>
  <% end %>
<% end %>

<% content_for :piedepagina do %>
  <p><span class='derechos'>Sistema de información de 
    <a href='https://github.com/pasosdeJesus/cor1440'>código abierto</a> con 
    <a href="https://github.com/pasosdeJesus/msip/blob/main/LICENCIA.md">licencia ISC</a>
    <br/>
    Desarrollado por <a id='pasosdeJesus' href="http://www.pasosdeJesus.org" target="_blank">Pasos de Jesús</a>. <%= Date.today.year %>.
<% end %>

<%= render template: "layouts/msip/application-prosidebar" %>

app/views/layouts/sip/application-dk1.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Cor1440 permite hacer seguimiento y evaluación de proyectos con marco lógico y susa actividades. ">
    <meta name="keywords" content="Cor1440, Marco lógico, monitore y evaluacion de proyectos">
    <meta name="author" content="Pasos de Jesús">


    <meta name="formato_fecha" content="<%= Rails.configuration.x.formato_fecha  ? Rails.configuration.x.formato_fecha : 'yyyy-mm-dd' %>">
    <title><%= content_for?(:titulo) ? yield(:titulo) : Sip.titulo %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all", 
      'data-turbo-track': 'reload' %>
    <%=  yield(:linkhref) if content_for?(:linkhref) %>

    <!-- Seguimios usando sprockets mientras:
      1. Pasamos javascript en assets/javascript a modulos
      2. Publicamos partes de gemas como paquetes npm -->
      <%= javascript_include_tag "application", defer: true %>
      <%= javascript_include_tag "recursos_sprockets", defer: true %>

      <!-- ****** favicons e ideas de enlaces de  faviconit.com ****** -->
      <%= favicon_link_tag 'favicon-16.png', :rel => 'icon', :type => 'image/png', :sizes => '16x16' %>
      <%= favicon_link_tag 'favicon-32.png', :rel => 'icon', :type => 'image/png', :sizes => '32x32' %>
      <%= favicon_link_tag 'favicon-64.png', :rel => 'icon', :type => 'image/png', :sizes => '64x64' %>
      <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon',  :sizes => '16x16 32x32 64x64' %>
      <%= favicon_link_tag 'favicon-96.png', :rel => 'icon', :type => 'image/png', :sizes => '96x96' %>
      <%= favicon_link_tag 'favicon-160.png', :rel => 'icon', :type => 'image/png', :sizes => '160x160' %>
      <%= favicon_link_tag 'favicon-192.png', :rel => 'icon', :type => 'image/png', :sizes => '192x192' %>
      <%= favicon_link_tag 'favicon-57.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
      <%= favicon_link_tag 'favicon-57.png', :rel => 'apple-touch-icon', :type => 'image/png' %>
      <%= favicon_link_tag 'favicon-60.png', :rel => 'apple-touch-icon', :size => '60x60', :type => 'image/png' %>
      <%= favicon_link_tag 'favicon-72.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
      <%= favicon_link_tag 'favicon-72.png', :rel => 'apple-touch-icon', :type => 'image/png', :sizes => '72x72' %>
      <%= favicon_link_tag 'favicon-76.png', :rel => 'apple-touch-icon', :size => '76x76', :type => 'image/png' %>
      <%= favicon_link_tag 'favicon-114.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
      <%= favicon_link_tag 'favicon-114.png', :rel => 'apple-touch-icon', :type => 'image/png', :sizes => '114x114' %>
      <%= favicon_link_tag 'favicon-120.png', :rel => 'apple-touch-icon', :type => 'image/png', :sizes => '120x120' %>
      <%= favicon_link_tag 'favicon-144.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
      <%= favicon_link_tag 'favicon-144.png', :rel => 'apple-touch-icon', :type => 'image/png', :sizes => '144x144' %>
      <%= favicon_link_tag 'favicon-152.png', :rel => 'apple-touch-icon', :type => 'image/png', :sizes => '152x152' %>
      <%= favicon_link_tag 'favicon-180.png', :rel => 'apple-touch-icon', :type => 'image/png', :sizes => '180x180' %>

      <meta name="msapplication-TileColor" content="#FFFFFF">
      <meta name="msapplication-TileImage" content="/assets/favicon-144.png">
      <meta name="msapplication-config" content="/assets/browserconfig.xml">

      <!-- dashboardkit 1.0 -->
      <link rel="stylesheet" href="<%=
      Pathname(Rails.configuration.relative_url_root).join(
        'dk1/assets/fonts/feather.css').to_s %>">
        <link rel="stylesheet" href="<%=
        Pathname(Rails.configuration.relative_url_root).join(
          'dk1/assets/fonts/fontawesome.css').to_s %>">
          <link rel="stylesheet" href="<%=
          Pathname(Rails.configuration.relative_url_root).join(
            'dk1/assets/fonts/material.css').to_s %>">
            <link rel="stylesheet" href="<%=
            Pathname(Rails.configuration.relative_url_root).join(
              'dk1/assets/css/style.css').to_s %>" id="main-style-link">
              <link rel="stylesheet" href="<%=
              Pathname(Rails.configuration.relative_url_root).join(
                'dk1/assets/css/personaliza-dk1.css').to_s %>">


  </head>
  <body>

    <!-- [ Pre-loader ] start -->
    <div class="loader-bg">
      <div class="loader-track">
        <div class="loader-fill"></div>
      </div>
    </div>
    <!-- [ Pre-loader ] End -->
    <!-- [ Mobile header ] start -->
    <div class="pc-mob-header pc-header">
      <div class="pcm-logo">
        <img src="<% Pathname(Rails.configuration.relative_url_root).join(
          'dk1/assets/fonts/feather.css').to_s %>"
          alt="" class="logo logo-lg">
      </div>
      <div class="pcm-toolbar">
        <a href="#!" class="pc-head-link" id="mobile-collapse">
          <div class="hamburger hamburger--arrowturn">
            <div class="hamburger-box">
              <div class="hamburger-inner"></div>
            </div>
          </div>
        </a>
      </div>
    </div>
    <nav class="pc-sidebar">
      <div class="navbar-wrapper">
        <div class="m-header">
          <a href="<%= Rails.configuration.relative_url_root.to_s %>" 
            class="b-brand"
            style="text-decoration: none" >
            <%= image_tag('logo-av2.png', 
                          class: 'logo logo-lg') %>
                        <span style='color: white'> Cor1440</span>
          </a>
        </div>
        <div class="navbar-content ps ps--active-y">
          <%= yield(:menu) if content_for?(:menu) %>
        </div>
      </div>
    </nav>

    <header class="pc-header">
      <div class="header-wrapper"> 
        <div class="mr-auto pc-mob-drp">
        </div>
        <div class="ml-auto">
          <ul class="list-unstyled">
            <li class="dropdown pc-h-item">
              <a class="pc-head-link dropdown-toggle arrow-none mr-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                <i class="material-icons-two-tone">search</i>
              </a>
              <div class="dropdown-menu dropdown-menu-right pc-h-dropdown drp-search">
                <form class="px-3">
                  <div class="form-group mb-0 d-flex align-items-center">
                    <i data-feather="search"></i>
                    <input type="search" class="form-control border-0 shadow-none" placeholder="Search here. . .">
                  </div>
                </form>
              </div>
            </li>
            <% if current_usuario %>
              <li class="dropdown pc-h-item">
                <a href="#" class="pc-head-link dropdown-toggle arrow-none mr-0"  data-bs-toggle="dropdown" role="button" aria-haspopup="false" aria-expanded="false">
                  <img src="<%= main_app.usuarios_foto_path(current_usuario.id) %>" 
                  alt="user-image" class="user-avtar">
                  <span>
                    <span class="user-name"><%= current_usuario.nusuario %></span>
                    <span class="user-desc"><%= Ability::ROLES.to_h.key(current_usuario.rol) %></span>
                  </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right pc-h-dropdown">
                  <a href="<%= main_app.editar_registro_usuario_path %>" class="dropdown-item">
                    <i class="material-icons">chrome_reader_mode</i>
                    <span>Clave y tema</span>
                  </a>
                  <a href="<%= main_app.sign_out_path %>" class="dropdown-item">
                    <i class="material-icons">
                      logout
                    </i>
                    <span>Salir</span>
                  </a>
                </div>
              </li>
            <% else %>
              <li class="pc-h-item">
                <a href="<%= main_app.new_usuario_session_path %>">
                  <i class="material-icons">
                    login
                  </i>
                  <span class="align-top"><%= I18n.t('Iniciar sesión') %></span>
                </a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>
    <!-- [ Main Content ] start -->
    <div class="pc-container">
      <%= anuncios_bootstrap %>
      <%= yield %>
      <% if content_for?(:piedepagina) %>
        <footer style='text-align: right'>
          <%= yield :piedepagina %>
        </footer>
      <% end %>
    </div> 
    <!-- pc-container -->
  </body>
</html>

app/views/usuarios/_campo_foto.html.erb
<!--% if !f.object || !f.object.id || !f.object.foto_file_name %-->
<%= f.input :foto, as: :file, label: t('fotojpgpngtiff'),
  input_html: { "data-imagenpre": 'imagen-detalle'} %>
<!--% else %-->
<% if f.object && f.object.id && f.object.foto_file_name %>
  <div class="foto_adjunto">
    <label for="foto_attributes_<%=f.object.id%>_adjunto"><%= t('Foto') %></label>
    <a id="foto_attributes_<%=f.object.id%>_adjunto" href="<%= main_app.usuarios_foto_path(f.object.id) %>", style="text-decoration:none"><%= f.object.foto_file_name %></a>
  </div>
<% end %>

app/views/usuarios/_show_foto.html.erb
<img src='<%= main_app.usuarios_foto_path(@registro.id) %>' style='max-height: 100px; max-width: 100px'>